### ISSUE TITLE
BUG: Comment section not updating

### ISSUE THREAD

**Issue by jindah** [jindah/picagram#22]
When user deletes a comment the section wont update. It deletes the comment but doesnt update the section.

**Comment by jindah** [comment]
One problem resolved:

```
              <Link onClick={handleDelete} className={styles.editDelete}>
                <i className="fa-solid fa-xmark"></i>
              </Link>
              <Link onClick={() => setShowEditForm(true)} className={styles.editDelete}>
                <i className="fa-solid fa-ellipsis"></i>
              </Link>
```
Link component  has to have a to prop. In React, the Link component from react-router-dom expects a to prop, and if it's missing, it will issue a warning.

changed them to span:

```
              <span onClick={handleDelete} className={styles.editDelete}>
                <i className="fa-solid fa-xmark"></i>
              </span>
              <span onClick={() => setShowEditForm(true)} className={styles.editDelete}>
                <i className="fa-solid fa-ellipsis"></i>
              </span>
```

**Comment by jindah** [comment]
Still getting this error:

Comment.js:48 Error deleting comment: TypeError: setPost is not a function
    at handleDelete (Comment.js:32:1)

**Comment by jindah** [comment]
same thing when trying to update a comment:

TypeError: setComments is not a function
    at handleSubmit (CommentEditForm.js:23:1)

**Comment by jindah** [comment]
problem solved. I missed to write setPost={setPost} etc to Comment component in PostPage.js:

```
                <Comment
                key={comment.id}
                {...comment}
                setPost={setPost}
                setComments={setComments}
                />
```

**Comment by jindah** [comment]
These console logs helpt me to solve the problem:

```
  const handleDelete = async () => {
    try {
      console.log('Deleting comment:', id);
      await axiosRes.delete(`/comments/${id}/`);
  
      console.log('Updating post and comments...');
      setPost((prevPost) => ({
        results: [
          {
            ...prevPost.results[0],
            comments_count: prevPost.results[0].comments_count - 1,
          },
        ],
      }));
  
      setComments((prevComments) => ({
        ...prevComments,
        results: prevComments.results.filter((comment) => comment.id !== id),
      }));
  
      console.log('Comment deleted successfully');
    } catch (err) {
      console.error('Error deleting comment:', err);
    }
  };
```
